import { Dosis } from "next/font/google";
import "./globals.css";
import { WagmiProvider } from "@/config/WagmiProvider";
import { ReduxProvider } from "@/store/provider";
import { TrackTxnProvider } from "@/config/TrackTxnProvider";
import { ModalProvider } from "@/config/ModalProvider";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dosis.className}>
        <WagmiProvider>
          <ReduxProvider>
            <TrackTxnProvider>
              <ModalProvider>{children}</ModalProvider>
            </TrackTxnProvider>
          </ReduxProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
